import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display } from "next/font/google"; // ← เพิ่ม
import "./globals.css";
import TopMenu from "@/components/TopMenu";
import { getServerSession } from "next-auth";
import NextAuthProvider from "@/providers/NextAuthProvider";
import { authOptions } from "./api/auth/[...nextauth]/authOptions";
import ReduxProvider from "@/redux/ReduxProvider";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

// ← เพิ่มตรงนี้
const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  variable: "--font-playfair",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const nextAuthSession = await getServerSession(authOptions);
  return (
    <html lang="en">
      {/* ← เพิ่ม playfair.variable */}
      <body className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable}`}>
            <ReduxProvider>
                <NextAuthProvider session={nextAuthSession}>
                    <TopMenu />
                    <main className="pt-16"> {/* ← เพิ่ม pt-16 */}
                        {children}
                    </main>
                </NextAuthProvider>
            </ReduxProvider>
        </body>
    </html>
  );
}